### ISSUE TITLE
Project Peer Review

### ISSUE THREAD

**Issue by brianacampos** [ines-pl/Project-#1]
First off, I really like your website! I think it gives viewers a good idea of what Portugal is like!

**2 technical issues/bugs/suggestions**

- Issue #1: As I was sliding through the pictures on the home screen, I realized that one of them was not showing up. I looked at you code and it seems to be a typo because there is a space. This is the line I am referring to:
https://github.com/ines-pl/Project-/blob/0c6627e226bc7e1bc47f1688558e40ff1986553d/index.html#L236

- Issue #2: For the music page, I would suggest to center the videos, or even make a table out of them. I think that would make it a lot more appealing to the eye!

**2 suggestions on content**

- Issue #1: I would suggest to add a bit more to the language page. I think it would be helpful to add a youtube video or even a translator (I think you can code google translate into your page). I definitely think it would be a great addition!

- Issue #2: I also would suggest to add a little icon to the top of your page. It's called a favicon and its the little icon that you see when clicking on a tab. I think it adds more personalization to the webpage! It's also linked by the professor on the resources GitHub!

Overall, I think your webpage is very nice and laid out well! It's simple and not too chaotic.

**Comment by ines-pl** [comment]
Thank you for all the recommendations. I will be sure to implement them.
