### ISSUE TITLE
Project Peer Review

### ISSUE THREAD

**Issue by ngarcia2024** [ines-pl/Project-#2]
Overall, I really enjoyed your website. I liked the background that you chose and the homepage was great. All the links worked and were very informative. 

Content Suggestions:
1.  I think you could add some more margins or breaks in the page for the history section, so it is easier to read and more separated. 
2. Another content suggestion would be to rearrange the navigation bar so that music and recipes are in the middle and not contact and sitemap. I think that would make it easier to navigate and see. 

Technical Suggestions:
1.  For some reason, the favicon was not showing up for me. I think you should double-check the "href" and make sure it is connected to the folder where you have the favico. 
2.  The second technical suggestion would be to look at the 3rd slide on the homepage "history". The image is not coming up for me. I am not sure why but that is something you can look into.

**Comment by ines-pl** [comment]
Thank you for all the recommendations. I will be sure to implement them.
